spring:
  datasource:
    username: root
    password: mxr2017
    url: jdbc:mysql://39.104.25.156:3306/chat_service?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver